package view;



import MVC.View;

import javax.swing.*;
import java.awt.event.KeyEvent;
import java.io.*;
import java.net.Socket;
import java.util.Objects;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author xaLuG
 */
public class MudarCategoria extends javax.swing.JFrame implements View{

    /**
     * Creates new form MudarCategoria
     */
    public MudarCategoria(Socket s, String nome, String artista,Musicas_Lista v) {
        this.nome=nome;
        this.artista=artista;
        this.tabela=v;
        this.socket=s;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        voltartras = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+ File.separator
                +"src"+File.separator+"view"+File.separator+"icons"+File.separator+"mediacenter.png")); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        voltartras.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+ File.separator
                +"src"+File.separator+"view"+File.separator+"icons"+File.separator+"back.png")); // NOI18N
        voltartras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltartrasActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione Categoria>", "Blues", "Classical", "Country", "Eletro", "Fado", "Funk", "Hip Hop", "Indie", "Jazz", "Kizomba", "Latin", "Metal", "Pop", "R&B", "Rap", "Reggae", "Rock", "Sertanejo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(voltartras))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(112, 112, 112)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(133, 133, 133)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(voltartras)
                                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String novogen = Objects.requireNonNull(jComboBox1.getSelectedItem()).toString();
        if (novogen.equals("<Selecione Categoria>")){
            JOptionPane.showMessageDialog(this, "Genero invalido");
        }
        else {
            String fich = this.nome + " - " + this.artista + ".mp3";
            try {
                PrintWriter pw = new PrintWriter(this.socket.getOutputStream());
                pw.println("alteraCategoria?" + fich + "?" +novogen);
                pw.flush();
                BufferedReader br = new BufferedReader(new InputStreamReader(this.socket.getInputStream()));
                String res = br.readLine();
                if (!res.equals("Sucesso")){
                    JOptionPane.showMessageDialog(this, res);
                    return;
                }
            }
            catch (IOException e){
                JOptionPane.showMessageDialog(this, "Erro de conexão");
                return;
            }
            new Reproduzir_Musica(this.socket, this.nome, this.artista,this.tabela).run();
            this.setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void categoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_categoriaKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER) {
            jButton1.doClick();
        }
    }//GEN-LAST:event_categoriaKeyPressed

    private void voltartrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltartrasActionPerformed
        new Reproduzir_Musica(this.socket,this.nome,this.artista,this.tabela).run();
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_voltartrasActionPerformed


    public void run() {
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setSize(430,330);
        this.setVisible(true);
    }


    private String nome;
    private String artista;
    private Socket socket;
    private Musicas_Lista tabela;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton voltartras;
    // End of variables declaration//GEN-END:variables
}
