#!/usr/bin/gawk -f

    { notas[$2][$1] = $3 }


END { for ( aluno in notas) {
        print aluno
        for (tp in notas[aluno] ) {
           print "\t" tp, notas[aluno][tp]
        }
      }
    }

